config/routes.rb
EuQueroEventos::Application.routes.draw do
  devise_for :contas,:controllers => {:registrations => "registrations"}

  root :to => 'tags#index'

  resources :mensagens

  resources :contatos

  resources :listas_contato

  resources :comentario_eventos

  resources :eventos

  resources :tags

  resources :contas

  resources :usuarios

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(contaAtual)
    contaAtual ||= Conta.new #visitante
    
    if contaAtual.perfil_id = 2
      can :manage,:all
    else
      
      #Regras de Evento
      can :create, Evento
      can :read, Evento
      can :update, Evento do |evento|
        evento.try(:usuario) == contaAtual.usuario
      end
      can :delete, Evento do |evento|
        evento.try(:usuario) == contaAtual.usuario
      end
      
      #Regras de Conta
      can :create, Conta
      can :read, Conta
      can :update, Conta do |conta|
        conta.try(:usuario) == contaAtual.usuario
      end
      can :delete, Evento do |evento|
        conta.try(:usuario) == contaAtual.usuario
      end
      
      #Regras Cidade/Estado
      can :read,Cidade
      can :read,Estado
      
      
    end
    
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities    
    
  end
end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
  attr_accessible :nome,:ativo
  has_many :eventos
  validates :nome,:ativo, :presence=>true
  validates :nome,:length=> { :maximum => 30 }
end

app/models/cidade.rb
class Cidade < ActiveRecord::Base
  attr_accessible :nome,:estado_id
  belongs_to :estado
  has_many :usuarios
  has_many :eventos

  validates :nome,:estado_id, :presence =>true
  validates :nome,:length=> { :maximum => 50 }

  def self.find_by_estado_id(estado_id)
    find(:all, :conditions => ["estado_id = ?", estado_id])
  end
  
end

app/models/conta.rb
class Conta < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :perfil
  has_one :usuario,:autosave=>true
  accepts_nested_attributes_for :usuario
  
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :perfil_id, :password, :password_confirmation, :remember_me, :ativo, :dataCadastro,:usuario_attributes
  validates :email,:uniqueness=>true,
            :format =>{:with=> /^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i}
  
end

app/models/contato.rb
class Contato < ActiveRecord::Base
	belongs_to :lista_contato
	has_many :usuarios
	attr_accessible :alteracao, :inclusao, :lista_contato_id, :status_contato_id, :usuario_id  
	validates :inclusao,:alteracao,:lista_contato_id, :status_contato_id, :usuario_id, :presence=>true
end

app/models/estado.rb
class Estado < ActiveRecord::Base
  attr_accessible :uf
  has_many :cidades
  validates :uf, :presence=>true
end

app/models/evento.rb
class Evento < ActiveRecord::Base
	attr_accessible :categoria_id, :cidade_id, :descricao, :endereco, :fim, :gratuito, :inicio, :limitado, :maioridade, :nome, :privado, :status_evento_id, :usuario_id, :vagas_disponiveis,
	 :vagas_oferecidas, :tipo_evento
	belongs_to :usuario
	belongs_to :status_evento
	belongs_to :categoria
	validates :categoria_id,:descricao,:fim, :gratuito, :inicio, :limitado,:maioridade, :nome, :privado, :status_evento_id, :usuario_id, :presence=>true
end

app/models/lista_contato.rb
class ListaContato < ActiveRecord::Base
  attr_accessible :nome, :padrao, :privada, :usuario_id
  has_many :contatos
  belongs_to :usuario
  validates :nome, :padrao, :privada, :usuario_id, :presence=>true
end

app/models/mensagem.rb
class Mensagem < ActiveRecord::Base
  attr_accessible :assunto, :dataEnvio, :mensagem, :status_mensagem, :remetente, :destinatario
  belongs_to :usuario,:class_name => 'remetente', :foreign_key => 'remetente_id'
  belongs_to :usuario,:class_name => 'destinatario', :foreign_key => 'destinatario_id'
  belongs_to :status_mensagem
  validates :assunto, :mensagem,:presence=>true
end

app/models/perfil.rb
class Perfil < ActiveRecord::Base
  attr_accessible :nome, :ativo
  has_one :conta
  validates :nome,:ativo, :presence=>true
  validates :nome,:length=> { :maximum => 50 }
end

app/models/status_contato.rb
class StatusContato < ActiveRecord::Base
  attr_accessible :nome, :codigo
  has_many :contatos
  validates :nome, :codigo, :presence=>true
end

app/models/status_evento.rb
class StatusEvento < ActiveRecord::Base
  attr_accessible :nome, :codigo
  has_many :eventos
  validates :nome, :codigo, :presence=>true
end

app/models/status_mensagem.rb
class StatusMensagem < ActiveRecord::Base
  attr_accessible :nome, :codigo
  has_many :mensagens
  validates :nome, :codigo, :presence=>true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible	:nome, :ativo
  validates :nome,:presence =>true,
            :length =>{:maximum=>20}
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
	attr_accessible :usuario, :nome, :sexo, :website, :cidade_id, :conta_id
	validates :nome, :presence =>true
	validates :nome,:webSite, :length=> { :maximum => 100 }

	belongs_to :cidade
	belongs_to :conta
	has_many :mensagens
	has_many :eventos

end

app/controllers/contatos_controller.rb
class ContatosController < ApplicationController
   load_and_authorize_resource

  # GET /contatos
  # GET /contatos.json
  def index
    @contatos = Contato.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contatos }
    end
  end

  # GET /contatos/1
  # GET /contatos/1.json
  def show
    @contato = Contato.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contato }
    end
  end

  # GET /contatos/new
  # GET /contatos/new.json
  def new
    @contato = Contato.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contato }
    end
  end

  # GET /contatos/1/edit
  def edit
    @contato = Contato.find(params[:id])
  end

  # POST /contatos
  # POST /contatos.json
  def create
    @contato = Contato.new(params[:contato])

    respond_to do |format|
      if @contato.save
        format.html { redirect_to @contato, notice: 'Contato was successfully created.' }
        format.json { render json: @contato, status: :created, location: @contato }
      else
        format.html { render action: "new" }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contatos/1
  # PUT /contatos/1.json
  def update
    @contato = Contato.find(params[:id])

    respond_to do |format|
      if @contato.update_attributes(params[:contato])
        format.html { redirect_to @contato, notice: 'Contato was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contatos/1
  # DELETE /contatos/1.json
  def destroy
    @contato = Contato.find(params[:id])
    @contato.destroy

    respond_to do |format|
      format.html { redirect_to contatos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cidades_helper.rb
module CidadesHelper
end

app/helpers/contas_helper.rb
module ContasHelper
end

app/helpers/contatos_helper.rb
module ContatosHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/mensagens_helper.rb
module MensagensHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/contatos/_form.html.erb
<%= form_for(@contato) do |f| %>
  <% if @contato.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contato.errors.count, "error") %> prohibited this contato from being saved:</h2>

      <ul>
      <% @contato.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lista_contato_id %><br />
    <%= f.number_field :lista_contato_id %>
  </div>
  <div class="field">
    <%= f.label :usuario_id %><br />
    <%= f.number_field :usuario_id %>
  </div>
  <div class="field">
    <%= f.label :status_contato_id %><br />
    <%= f.number_field :status_contato_id %>
  </div>
  <div class="field">
    <%= f.label :inclusao %><br />
    <%= f.datetime_select :inclusao %>
  </div>
  <div class="field">
    <%= f.label :alteracao %><br />
    <%= f.datetime_select :alteracao %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contatos/edit.html.erb
<h1>Editing contato</h1>

<%= render 'form' %>

<%= link_to 'Show', @contato %> |
<%= link_to 'Back', contatos_path %>

app/views/contatos/index.html.erb
<h1>Listing contatos</h1>

<table>
  <tr>
    <th>Lista contato</th>
    <th>Usuario</th>
    <th>Status contato</th>
    <th>Inclusao</th>
    <th>Alteracao</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contatos.each do |contato| %>
  <tr>
    <td><%= contato.lista_contato_id %></td>
    <td><%= contato.usuario_id %></td>
    <td><%= contato.status_contato_id %></td>
    <td><%= contato.inclusao %></td>
    <td><%= contato.alteracao %></td>
    <td><%= link_to 'Show', contato %></td>
    <td><%= link_to 'Edit', edit_contato_path(contato) %></td>
    <td><%= link_to 'Destroy', contato, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contato', new_contato_path %>

app/views/contatos/new.html.erb
<h1>New contato</h1>

<%= render 'form' %>

<%= link_to 'Back', contatos_path %>

app/views/contatos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Lista contato:</b>
  <%= @contato.lista_contato_id %>
</p>

<p>
  <b>Usuario:</b>
  <%= @contato.usuario_id %>
</p>

<p>
  <b>Status contato:</b>
  <%= @contato.status_contato_id %>
</p>

<p>
  <b>Inclusao:</b>
  <%= @contato.inclusao %>
</p>

<p>
  <b>Alteracao:</b>
  <%= @contato.alteracao %>
</p>


<%= link_to 'Edit', edit_contato_path(@contato) %> |
<%= link_to 'Back', contatos_path %>